name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        uses: psf/black@stable
        with:
          options: "--check --verbose -l 120"
          src: "./app"
          version: "~= 22.0"
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install mypy
          pip install -r app/requirements.txt
      - name: Run mypy
        run: mypy .
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r app/requirements.txt
      - name: Run tests
        run: pytest
